### ISSUE TITLE
nohup.out

### ISSUE THREAD

**Issue by killua99** [kzar/caffeine#2]
Just to know what could be:

(caffeine:10243): Gdk-WARNING **: caffeine: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.

No idea what does mean.

**Comment by kzar** [comment]
I'm not sure to be honest. That command runs caffeine the first time, after that it should start automatically when you log in. Have you tried just rebooting your computer and seeing if caffeine starts automatically?

**Comment by kzar** [comment]
Are you still having this problem? I can't reproduce it.
